"""J16 rule-skills catalog (26 checks) — metadata + availability hints."""
from __future__ import annotations

from typing import Any

# id, zone, severity, title, recommendation, run_when
RULE_CATALOG: list[dict[str, Any]] = [
    {"id": "semantics_top3_concentration", "zone": "semantics", "severity": "high",
     "title": "Концентрация расхода в топ-3 условиях",
     "recommendation": "Расширить семантику и добавить минус-слова.",
     "run_when": "conditions_summary.top_by_spend ≥ 3"},
    {"id": "semantics_top3_concentration_warn", "zone": "semantics", "severity": "medium",
     "title": "Заметная концентрация в топ-3 условиях",
     "recommendation": "Проверить минус-слова и целевые формулировки.",
     "run_when": "share топ-3 ≥ 60%"},
    {"id": "semantics_high_spend_zero_leads", "zone": "semantics", "severity": "high",
     "title": "Расход без лидов в условиях показа",
     "recommendation": "Минус-слова и снижение ставок по неэффективным условиям.",
     "run_when": "high_spend_zero_leads не пуст"},
    {"id": "semantics_cpl_dispersion", "zone": "semantics", "severity": "medium",
     "title": "Разброс CPL между условиями",
     "recommendation": "Перенести бюджет в условия с лучшим CPL.",
     "run_when": "best/worst CPL ≥ 4×"},
    {"id": "semantics_autotarget_share", "zone": "semantics", "severity": "medium",
     "title": "Высокая доля автотаргетинга",
     "recommendation": "Сузить автотаргетинг, усилить ручную семантику.",
     "run_when": "autotarget share ≥ 45%"},
    {"id": "semantics_narrow_base", "zone": "semantics", "severity": "low",
     "title": "Узкая база условий",
     "recommendation": "Расширить семантику и проверить охват.",
     "run_when": "unique_conditions < 30 при cost ≥ 50k"},
    {"id": "semantics_waste_share", "zone": "semantics", "severity": "medium",
     "title": "Доля слива в условиях без лидов",
     "recommendation": "Сократить неэффективные условия и минус-слова.",
     "run_when": "waste cost / total cost ≥ 15%"},
    {"id": "semantics_keyword_concentration", "zone": "semantics", "severity": "medium",
     "title": "Концентрация на ключевых фразах",
     "recommendation": "Диверсифицировать семантику.",
     "run_when": "keyword/phrase share ≥ 55%"},
    {"id": "campaigns_budget_concentration", "zone": "campaigns", "severity": "medium",
     "title": "Бюджет в одной кампании",
     "recommendation": "Перераспределить бюджет.",
     "run_when": "top campaign share ≥ 55%"},
    {"id": "campaigns_spend_no_leads", "zone": "campaigns", "severity": "high",
     "title": "Кампании с расходом без лидов",
     "recommendation": "Пауза или пересмотр настроек.",
     "run_when": "cost ≥ 5000 и leads = 0"},
    {"id": "campaigns_cpl_spread", "zone": "campaigns", "severity": "medium",
     "title": "Разброс CPL между кампаниями",
     "recommendation": "Масштабировать эффективные кампании.",
     "run_when": "worst/best CPL ≥ 3×"},
    {"id": "campaigns_leads_concentration", "zone": "campaigns", "severity": "low",
     "title": "Лиды в одной кампании",
     "recommendation": "Проверить потенциал остальных кампаний.",
     "run_when": "leads share ≥ 75%"},
    {"id": "campaigns_low_conversion", "zone": "campaigns", "severity": "high",
     "title": "Клики без конверсий",
     "recommendation": "Проверить посадочные и цели.",
     "run_when": "clicks ≥ 100 и leads = 0"},
    {"id": "dynamics_short_history", "zone": "dynamics", "severity": "low",
     "title": "Короткая история по месяцам",
     "recommendation": "Загрузить более длинный период.",
     "run_when": "monthly < 2"},
    {"id": "dynamics_cpl_volatility", "zone": "dynamics", "severity": "medium",
     "title": "Нестабильный CPL",
     "recommendation": "Проверить сезонность и ставки.",
     "run_when": "CV CPL ≥ 0.45"},
    {"id": "dynamics_leads_drop", "zone": "dynamics", "severity": "medium",
     "title": "Падение лидов",
     "recommendation": "Разобрать ставки и семантику.",
     "run_when": "последний месяц −30% лидов"},
    {"id": "dynamics_cpl_rise", "zone": "dynamics", "severity": "medium",
     "title": "Рост CPL",
     "recommendation": "Оптимизировать ставки.",
     "run_when": "CPL +25% к пред. месяцу"},
    {"id": "dynamics_month_leads_gap", "zone": "dynamics", "severity": "low",
     "title": "Разброс лидов по месяцам",
     "recommendation": "Закрепить практики лучшего месяца.",
     "run_when": "gap лидов ≥ 10"},
    {"id": "dynamics_cost_spike", "zone": "dynamics", "severity": "medium",
     "title": "Скачок расхода",
     "recommendation": "Проверить ставки и бюджеты.",
     "run_when": "cost +40% к пред. месяцу"},
    {"id": "dynamics_zero_leads_month", "zone": "dynamics", "severity": "high",
     "title": "Месяц с расходом без лидов",
     "recommendation": "Проверить цели и трекинг.",
     "run_when": "month cost ≥ 5k и leads = 0"},
    {"id": "data_quality_spend_no_leads", "zone": "data_quality", "severity": "critical",
     "title": "Расход без лидов за период",
     "recommendation": "Проверить цели Метрики.",
     "run_when": "totals cost ≥ 10k, leads = 0"},
    {"id": "data_quality_high_account_cpl", "zone": "data_quality", "severity": "medium",
     "title": "CPL выше среднего по месяцам",
     "recommendation": "Снизить CPL.",
     "run_when": "account CPL > avg monthly × 1.35"},
    {"id": "data_quality_channel_imbalance", "zone": "data_quality", "severity": "low",
     "title": "Дисбаланс форм и мессенджеров",
     "recommendation": "Проверить креативы и посадочные.",
     "run_when": "forms/messenger ratio > 5×"},
    {"id": "ml_monthly_anomaly", "zone": "dynamics", "severity": "medium",
     "title": "Аномалия по месяцам (IQR)",
     "recommendation": "Проверить всплески расхода/CPL.",
     "run_when": "monthly ≥ 4, outlier IQR"},
    {"id": "ml_campaign_underperformers", "zone": "campaigns", "severity": "medium",
     "title": "Кампании-аутсайдеры",
     "recommendation": "Перераспределить бюджет.",
     "run_when": "campaigns ≥ 3, нижняя треть"},
    {"id": "ml_cpl_high_cv", "zone": "dynamics", "severity": "medium",
     "title": "Высокая волатильность CPL (ML)",
     "recommendation": "Стабилизировать ставки.",
     "run_when": "CV ≥ 0.5 без дубля dynamics"},
]


def get_rule_catalog() -> list[dict[str, Any]]:
    return [dict(item) for item in RULE_CATALOG]


def catalog_entry(rule_id: str) -> dict[str, Any] | None:
    for item in RULE_CATALOG:
        if item["id"] == rule_id:
            return dict(item)
    return None
