/** Legacy registers callbacks here to break circular imports (H1+). */
export const runtimeBridge = {
    getCurrentAuditId: () => null,
    getAuditIdFromUrl: () => null,
    getAuditData: () => null,
    setAuditData: (_data) => {},
    getDocumentIssueContext: () => null,
    setDocumentIssueContext: (_value) => {},
    applyDocumentModalGuidance: (_itemId) => {},
    getMediaRecorder: () => null,
    clearEditingMaterialId: () => {},
    getPrivacySettings: () => null,
    loadPrivacySettings: async () => {},
    buildAnalysisPayload: async () => null,
    applyRoleUiRestrictions: () => {},
    applyAdminUiSegmentation: () => {},
    onClientSaved: (_auditId, _updated) => {},
    onAuthSessionChanged: async () => {},
    onAuthLogoutNavigate: async () => {},
    renderAuditDetail: (_data) => {},
    renderFindings: (_findings, _coverage) => {},
    switchTab: (_tab) => {},
    openModal: (_id) => {},
    closeModal: (_id) => {},
    openMetricsEditor: (_focusIssue, _materialId) => {},
    openMetricsEditorEdit: (_materialId) => {},
    scrollToMetricsPeriodsPanel: () => {},
    openMetricsEditorForNewPeriod: (_focusIssue) => {},
    openNewMaterial: (_modalId) => {},
    openDataItemAction: (_itemId, _issue) => {},
    editMaterial: (_id) => {},
    getMaterialById: (_id) => null,
    goToAddAuditData: async () => {},
    loadAuditDetail: async () => {},
    runAuditAnalysis: (_forceDraft) => {},
    openReportPanel: () => {},
    acceptDataLimitation: async (_itemId) => {},
    updateExtractMetricsButtonVisibility: (_data) => {},
    getStatusLabel: (_status) => '',
    renderAnalysisStaleBar: (_data) => {},
    renderCoverageProgress: (_coverage) => {},
    isAnalysisLikelyStuck: (_data) => false,
    resetStuckAnalysis: async () => {},
    showAnalysisProgress: (_payload) => {},
    hideAnalysisProgress: () => {},
    connectAnalysisProgress: (_auditId) => {},
    goToDataImprovements: async () => {},
    isAnalysisStale: (_data) => false,
    focusScrollTarget: (_el) => {},
    loadKbStatusCard: () => {},
    getCurrentScreenState: () => 'UNKNOWN',
    renderChatHistory: () => {},
    askInChat: async (_opts) => {},
    loadComparison: () => {},
    getSelectedModelId: (_scope) => null,
    fillMetricsFromSummary: (_summary) => {},
    focusMetricsModalField: () => {},
};

export function configureRuntimeBridge(partial) {
    Object.assign(runtimeBridge, partial);
}
